services:
  - type: web
    name: api-secti-backend
    runtime: node
    region: ohio
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && node --import tsx/esm src/server.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: '20'
